export const browserCoreExamples = [
  "hassoon browser status",
  "hassoon browser start",
  "hassoon browser stop",
  "hassoon browser tabs",
  "hassoon browser open https://example.com",
  "hassoon browser focus abcd1234",
  "hassoon browser close abcd1234",
  "hassoon browser screenshot",
  "hassoon browser screenshot --full-page",
  "hassoon browser screenshot --ref 12",
  "hassoon browser snapshot",
  "hassoon browser snapshot --format aria --limit 200",
];

export const browserActionExamples = [
  "hassoon browser navigate https://example.com",
  "hassoon browser resize 1280 720",
  "hassoon browser click 12 --double",
  'hassoon browser type 23 "hello" --submit',
  "hassoon browser press Enter",
  "hassoon browser hover 44",
  "hassoon browser drag 10 11",
  "hassoon browser select 9 OptionA OptionB",
  "hassoon browser upload /tmp/file.pdf",
  'hassoon browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "hassoon browser dialog --accept",
  'hassoon browser wait --text "Done"',
  "hassoon browser evaluate --fn '(el) => el.textContent' --ref 7",
  "hassoon browser console --level error",
  "hassoon browser pdf",
];
