name: Hassoon
options:
  bundleIdPrefix: com.moeghashim.hassoon
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

packages:
  HassoonKit:
    path: ../shared/HassoonKit
  Swabble:
    path: ../../Swabble

schemes:
  Hassoon:
    shared: true
    build:
      targets:
        Hassoon: all
    test:
      targets:
        - HassoonTests

targets:
  Hassoon:
    type: application
    platform: iOS
    sources:
      - path: Sources
    dependencies:
      - package: HassoonKit
      - package: HassoonKit
        product: HassoonChatUI
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    preBuildScripts:
      - name: SwiftFormat (lint)
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftformat >/dev/null 2>&1; then
            echo "error: swiftformat not found (brew install swiftformat)" >&2
            exit 1
          fi
          swiftformat --lint --config "$SRCROOT/../../.swiftformat" \
            --filelist "$SRCROOT/SwiftSources.input.xcfilelist"
      - name: SwiftLint
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftlint >/dev/null 2>&1; then
            echo "error: swiftlint not found (brew install swiftlint)" >&2
            exit 1
          fi
          swiftlint lint --config "$SRCROOT/.swiftlint.yml" --use-script-input-file-lists
    settings:
      base:
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: Y5PE65HELJ
        PRODUCT_BUNDLE_IDENTIFIER: com.moeghashim.hassoon.ios
        PROVISIONING_PROFILE_SPECIFIER: "com.moeghashim.hassoon.ios Development"
        SWIFT_VERSION: "6.0"
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: Hassoon
        CFBundleIconName: AppIcon
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIBackgroundModes:
          - audio
        NSLocalNetworkUsageDescription: Hassoon discovers and connects to your Hassoon bridge on the local network.
        NSAppTransportSecurity:
          NSAllowsArbitraryLoadsInWebContent: true
        NSBonjourServices:
          - _hassoon-bridge._tcp
        NSCameraUsageDescription: Hassoon can capture photos or short video clips when requested via the bridge.
        NSMicrophoneUsageDescription: Hassoon needs microphone access for voice wake.
        NSSpeechRecognitionUsageDescription: Hassoon uses on-device speech recognition for voice wake.

  HassoonTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: Hassoon
      - package: Swabble
        product: SwabbleKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.moeghashim.hassoon.ios.tests
        SWIFT_VERSION: "6.0"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Hassoon.app/Hassoon"
        BUNDLE_LOADER: "$(TEST_HOST)"
    info:
      path: Tests/Info.plist
      properties:
        CFBundleDisplayName: HassoonTests
